### ISSUE TITLE
New Test Run Created Instead of Updating Existing Run When "Relaunch Failed on CI" is Clicked in Testomatio

### ISSUE THREAD

**Issue by ZeroDayD** [testomatio/app#1119]
The issue arises when a test run is not created directly from Testomatio (e.g., when initiated by a custom workflow in CI). In such cases, when the "Relaunch failed on CI" button in Testomatio is clicked, a new test run is created instead of updating the existing one. This behavior seems logical, as a different workflow is triggered (the one specified in the test machine settings, such as in testomatio.yml).

However, perhaps if the old TESTOMATIO_RUN is used, the reports could be merged into a single test run?

I suggest always passing TESTOMATIO_RUN when the "Relaunch failed on CI" button is clicked.

**Steps:**

1a. Create a GitHub Action job with reporting to Testomat.

Example 1 (with a custom npm script input):
```
- name: Run tests
  run: npx start-test-run -c "npm run ${{ github.event.inputs.script }}"
  env:
    TESTOMATIO: ${{ TESTOMATIO_API_KEY }}
```

Example 2 (with a scheduled run):

```
- name: Run regression
  run: npx start-test-run -c "npm run regression"
  env:
    TESTOMATIO_TITLE="Nightly regression"
    TESTOMATIO: ${{ TESTOMATIO_API_KEY }}
```
1b. Run tests locally with reporting to Testomat.
2. Run this job manually (ensure there is at least one failed test).
3. Click "Relaunch failed on CI" in Testomat.

**Actual:** 
A new test run with the failed test is created in Testomat (a new TESTOMATIO_RUN ID is provided to the CI job). The default workflow specified in the Continuous Integration config is triggered.

**Expected:**
CI is triggered with the existing TESTOMATIO_RUN ID, and the test results are merged into the same report.

**Note:**
This issue cannot be reproduced if the initial run was created directly from Testomatio.
