### ISSUE TITLE
Error Unprocessable Entity (HTTP 422) Unexpected inputs provided: [\"grep\"] when input is not provided

### ISSUE THREAD

**Issue by andrewrybak** [testomatio/app#762]
**Describe the bug**
I can see the error `Unprocessable Entity (HTTP 422) Unexpected inputs provided: [\"grep\"]` for Java+Maven based project. Looks like grep is the default value, but Java projects do not support the **grep** feature.

**To Reproduce**
1. Make yml file without **grep** input
```
name: Trigger tests manually

on:
  workflow_dispatch:
    inputs:
      run:
        description: ''
        required: false
      testomatio:
        description: ''
        required: false

jobs:
  test:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Execute tests with Maven
      run: |
        mvn clean test
      env:
        TESTOMATIO: ${{ github.event.inputs.testomatio }}
        TESTOMATIO_RUN: ${{ github.event.inputs.run }}

    - name: Execute collection of metrics to the Testomat
      run: |
        npm i -g @testomatio/reporter
        TESTOMATIO=${{ github.event.inputs.testomatio }} npx report-xml "/home/runner/work/PoC-testomatio/PoC-testomatio/target/surefire-reports/**.xml" --java-tests=src/test/java
```

2. Configure automated test run
3. Configure GitHub Actions integrations
4. Launch test run from testomat
5. Observe the error

**Expected behavior**
**grep** is optional and not mandatory field in the yml file for GH workflow

**Screenshots**
Launch automated tests from testomat with such configurations
![image](https://github.com/testomatio/app/assets/134290917/3f97dbf0-2823-42e3-83bd-28a8271bd815)
![image](https://github.com/testomatio/app/assets/134290917/5c5697d9-3431-4b19-a4fe-ef83b8e3f05b)

Error
![image](https://github.com/testomatio/app/assets/134290917/70c33cc4-eb65-4861-ab10-a3738fb12966)

**Additional context**
Payload
```
{profile: "github", id: "26797ab6", type: "plan", override: {ref: "main"}}
id: "26797ab6"
override: {ref: "main"}
profile: "github"
type: "plan"
```
